<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>ReporterGenerator</Title>
        <Authors>Nicolas Medina</Authors>
    </PropertyGroup>

</Project>
